### ISSUE TITLE
Module Guid is 00000000-0000-0000-0000-000000000000

### ISSUE THREAD

**Issue by jhochwald** [zloeber/ModuleBuild#6]
- OS:  Windows 10 1709
- PowerShell Version:  5.1.16299.98 (Desktop)
- List the steps to reproduce the problem below (if possible attach a screenshot and/or link to the code): In all my builds the GUID is 00000000-0000-0000-0000-000000000000

Examples:

- All updatable Help Files located in `\release\X.X.X\en-US` (And the general release folder)
CAB: `et.General_00000000-0000-0000-0000-000000000000_en-US_HelpContent.cab`
ZIP: `et.General_00000000-0000-0000-0000-000000000000_en-US_HelpContent.zip`
XML: `et.General_00000000-0000-0000-0000-000000000000_HelpInfo.xml`
- The general MD File (Header) in `/docs`
In your case: [ModuleBuild.md](https://github.com/zloeber/ModuleBuild/release/ModuleBuild/docs/ModuleBuild.md) contains `Module Guid: 00000000-0000-0000-0000-000000000000`

As a Workaround a run a cleanup script after each build to rename the files and replace the MarkDown Header based on the real Guid from the Manifest.

**Comment by zloeber** [comment]
Pushing out 0.2.2 to the gallery now. Thanks for reporting this huge bug. I've inserted the replacement Guid in the CreateMarkdownHelp task. The module we feed into PlatyPS for creating help is the .psm1 file, not the actual manifest. When you load a .psm1 file the GUID (and many other properties) are ignored. But since we are building the psd1 file as part of our process (to insert exported functions and such) we cannot do that here. Chicken/egg scenario but inserting the Guid via the task should be cleaner than a post build script (which I've also fixed thanks to you!).

Cheers,
